spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/ms_market
    username: example
    password: example
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

permit-all-requests:
  get-list:
    - /swagger-ui
    - /v3/api-docs

logging:
  level:
    org:
      springframework.security: DEBUG

server:
  port: 9901

backend-service:
  key: "backend-key"
  url: "http://localhost:9902/backend"


