spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ms_user
    username: example
    password: example
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

permit-all-requests:
  get-list:
    - /swagger-ui
    - /v3/api-docs
    - /api/hello
  post-list:
    - /api/signup
    - /api/signin

logging:
  level:
    org:
      springframework.security: DEBUG

server:
  port: 9899

